### ISSUE TITLE
hey idk if u will see this, but please do

### ISSUE THREAD

**Issue by maxthespongebobguy** [CezarGab/Overlyrics#6]
just add me on discord because your app isnt working, here is what it has send to me

 User not registered in the Developer Dashboard, reason: None

**Comment by maxthespongebobguy** [comment]
truerobyian discord

**Comment by xtho25** [comment]
#5

**Comment by CezarGab** [comment]
Hello there! Thank you for using the project. 

I sent you an invite on the Discord to offer support.
