### ISSUE TITLE
No "No lyrics" message, old lyrics displaying instead.

### ISSUE THREAD

**Issue by xtho25** [CezarGab/Overlyrics#9]
I came accross this issue while listening: When a song with no lyrics starts playing, the lyrics from the previous song start playing with their timestamps instead of showing something like "This song has no lyrics.".
EDIT:When no previous song, it just gets stuck at "Starting..."

**Comment by CezarGab** [comment]
Hi! 

This is such an annoying bug that I also came across during development. I will try to fix it.

Thanks for reporting this.

**Comment by CezarGab** [comment]
Solved by xtho himself, he's on fire!🎉
